### ISSUE TITLE
I mean I'm thinking about licensing it under Unlicense but

### ISSUE THREAD

**Issue by dogtopus** [luatsenpai/rgss3a-fux2pack-header#1]
That ZiXueBei website stole my code without giving any credits. Here is my original post: https://gist.github.com/dogtopus/a9eee9e9f513d4975ea5cac252d406cc. It would be great if you can properly credit me.

(Not like I actually care lol. Never thought a byproduct of one of my RPG Maker game porting projects would actually be that popular)

**Comment by luatsenpai** [comment]
> That ZiXueBei website stole my code without giving any credits. Here is my original post: https://gist.github.com/dogtopus/a9eee9e9f513d4975ea5cac252d406cc. It would be great if you can properly credit me.
> 
> (Not like I actually care lol. Never thought a byproduct of one of my RPG Maker game porting projects would actually be that popular)

Sorry, I didn't know that, I just translate the tool into my language to make it easier to use

**Comment by dogtopus** [comment]
No problem. Just saw that you changed it so that's great.
